language: erlang
otp_release:
- 17.4
env:
- RMQ_TAG=v3_5_1 RMQ_VERSION=3.5.x GUN_COMMIT=a752035 GUN_VERSION=0.1.0 BUILD_DIR=$HOME/rabbitmq-public-umbrella
before_install:
- $TRAVIS_BUILD_DIR/travis-umbrella-setup.sh
install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y xsltproc
script: cd $BUILD_DIR/influxdb-storage-exchange && make test
before_deploy:
- cd $BUILD_DIR/influxdb-storage-exchange
- VERSION=$RMQ_VERSION make
cache:
  apt: true
  directories:
  - $BUILD_DIR
